### ISSUE TITLE
能不能把实现思路写一下哈 谢谢啦

### ISSUE THREAD

**Issue by liupengandroid** [WANZIzZ/RowingView#1]

**Comment by WANZIzZ** [comment]
可以 这个我抽空写一下

**Comment by WANZIzZ** [comment]
你可以看下 https://blog.csdn.net/u014068277/article/details/105473427 我的思路跟第一种差不多。 都是先搞一个自定义View出来，用来显示路径和移动的小船，然后放到RecyclerView里面去，最后去监听RecyclerView的滑动。大概思路就是这样，等基本功能实现后，再搞一个小船的View去代替原来的Bitmap。

**Comment by liupengandroid** [comment]
赞  谢谢老哥------------------ 原始邮件 ------------------
发件人: "乘风"<notifications@github.com>
发送时间: 2020年4月13日(星期一) 晚上8:17
收件人: "WANZIzZ/RowingView"<RowingView@noreply.github.com>;
抄送: "liupengandroid"<326401277@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [WANZIzZ/RowingView] 能不能把实现思路写一下哈 谢谢啦 (#1)




 
你可以看下 https://blog.csdn.net/u014068277/article/details/105473427 我的思路跟第一种差不多。 都是先搞一个自定义View出来，用来显示路径和移动的小船，然后放到RecyclerView里面去，最后去监听RecyclerView的滑动。大概思路就是这样，等基本功能实现后，再搞一个小船的View去代替原来的Bitmap。
 
&mdash;
